# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('options', models.TextField()),
                ('answer', models.IntegerField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
