# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='button_solution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
