# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20160209_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
