# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20160209_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
