# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_auto_20160209_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
