# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import tkupek_elearning.elearning.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_auto_20160214_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=tkupek_elearning.elearning.models.gen_token, max_length=40, null=True),
        ),
    ]
