# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='useransweroptions',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.UserAnswer'),
        ),
        migrations.AlterUniqueTogether(
            name='useransweroptions',
            unique_together=set([('user_answer', 'option')]),
        ),
    ]
