# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_auto_20160214_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
