# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0018_auto_20160221_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='button_solution',
            new_name='text_solution',
        ),
        migrations.AddField(
            model_name='setting',
            name='text_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
