# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import tkupek_elearning.elearning.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_setting_text_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='token',
            field=models.CharField(default=tkupek_elearning.elearning.models.gen_token, max_length=40, null=True),
        ),
    ]
