# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models
import tkupek_elearning.elearning.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0021_setting_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=tkupek_elearning.elearning.models.gen_token, max_length=40, null=True, unique=True),
        ),
    ]
