# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import tkupek_elearning.elearning.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0023_auto_20160305_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='token',
        ),
        migrations.AddField(
            model_name='setting',
            name='statistic_token',
            field=models.CharField(default=tkupek_elearning.elearning.models.gen_token, max_length=40, null=True, unique=True),
        ),
    ]
