# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0025_user_completed_message_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='popup_completed_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='popup_completed_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
