# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0027_auto_20160305_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
