# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0028_auto_20160305_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='completed_message_shown',
            new_name='completed',
        ),
    ]
