# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('questionTitle', models.CharField(max_length=100)),
                ('questionText', models.TextField()),
                ('questionAnswer', models.TextField()),
            ],
        ),
    ]
